class jugador{
+player 1

}

class turno{
+numerodeturnos
}
class movimientoarealizar{
+puñetazo
+uppercut
+defensa
+alta

}

class disparar{
+
}

class pierdes{

}
jugador --* turno
jugador --> movimientoarealizar
jugador --> disparar
disparar --* movimientoarealizar
jugador --> pierdes
